language: python
cache:
  directories:
    - "$HOME/.cache/pip"

notifications:
  email: false

branches:
  only:
    # Only build master and version tags
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

addons:
  apt:
    packages:
      - libopenblas-base

install:
  - pip3 install pyscf
  - pip3 install --verbose -r requirements.txt
script: python3 setup.py test -a '--cov=adcc'

# These jobs are only run with the first python version
# mentioned in the initial list
jobs:
  include:
    #
    # Checking
    - stage: code style
      python: 3.8
      addons:
        apt:
          packages: []   # Do not install openblas here
      install: travis_retry pip3 install flake8
      script: flake8
      env: CODE_STYLE="flake8"
    #
    # Testing
    - stage: test
      python: 3.6
      env: BUILD_SDIST=true
    - python: 3.8
    - os: osx
      language: script
      osx_image: xcode11.1  # macos 10.14

# TODO Does not work at the moment, see the travis output
# https://travis-ci.org/adc-connect/adcc/jobs/603309015#L2647
# after_success:
#    - pip3 install coveralls
#    - coveralls debug --verbose

deploy:  # Note: This will only deploy sdist on linux!
  skip_cleanup: true
  provider: pypi
  user: "__token__"
  password:
    secure: "M0IvnPighjcqz6UpKTjNfyuk0bObS8K+3MyYpVHlOHmwWT9/aKnrSQNI+se/khh3x8cSrsdjMWUMMGfWDWEHL+4BXOwsFIPx+34GghLxisbLy0EXKR6ziaMId28PYnLDUbqVLNANMn1s7H/vPseenbmslUrDR8QrTBstsQHIX7CvDqjT06/mfnx9EYAmknOemy222MXZhboYqjeBXtWZq+DHdukUqKLlJwLscV0cC+iOZx+16jkFkVf7xqlc1MbzPUTfFCUUSxGBafGLPWcI0mcgjvuLxAQv9B6HXEZpyaLK5C+Iw2aRUAnIovdyRwOgc1r8pTZ5Zpzat6uhadlb8gETeFdAan8sbRZ6GYbSV31mCHr6pN35N3dRXx6qybCwQGT+pZTPisEEnsR50TqkeI9NiYe0lgU4lE7Ej85kdFdB0w/B3JdanjCrLJNQia7euLPoWA+QAXsMUD8xm57UrrpMX/JsCGMBIajzJOQGoSDPmX72oEWkke3ctobCWBBtslmNYFowj+2aE+1REwSpBR879lK+rudhM2WRFqwbc4JXiCNTWH61exnT5yn3ksDPquCJSQRSLPc7tXQr24TElMtT76UrK2k8DTjj8digAJ2z7kSG5WOc17gj4LoyQMot7Q+ASdWIlBlU1JprsPHpZhPG45iAAJ0E/598Jfm22l8="
  on:
    tags: true
    all_branches: true
    condition: "$BUILD_SDIST == true"
