name: adcc-dev
channels:
  - conda-forge
dependencies:
  # Build
  - python
  - gcc_linux-64 =9.4
  - gxx_linux-64 =9.4
  - libtensorlight =3.0.1=hc894906_1
  - pybind11 >=2.6
  # Run
  - numpy >=1.14,<1.24 # problems with PE in pyscf for 1.24
  - scipy >=1.2
  - tqdm >=4.30
  - h5py >=2.9
  - opt_einsum >=3.0
  # Tests
  - pandas >=0.25.0
  - cppe >=0.3.1
  - pytest
  - pytest-cov
  - pyyaml
  - lcov
  - pip:
    - pyscf
