name: adcc-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Build
  - python
  - gcc_linux-64
  - gxx_linux-64
  - libtensorlight >=3.0.1
  - pybind11 >=2.6
  - pip
  # Run
  - numpy >=1.14
  - scipy >=1.2
  - tqdm >=4.30
  - h5py >=2.9
  - opt_einsum >=3.0
  # Tests
  - pandas >=0.25.0
  - cppe >=0.3.1
  - pytest
  - pytest-cov
  - lcov
  - pip:
    - pyscf
